
export const ERROR_CODES = {
    // Validation
    VALIDATION_ERROR: "VALIDATION_ERROR",
    BAD_REQUEST: "BAD_REQUEST",
  
    // Authentication & Authorization
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    INVALID_TOKEN: "INVALID_TOKEN",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    OTP_INVALID: "OTP_INVALID",
    OTP_EXPIRED: "OTP_EXPIRED",
  
    // Resources
    NOT_FOUND: "NOT_FOUND",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    NOTE_NOT_FOUND: "NOTE_NOT_FOUND",
  
    // Conflict
    CONFLICT: "CONFLICT",
    USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
    EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  
    // Rate Limiting
    TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  
    // Server
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    DATABASE_ERROR: "DATABASE_ERROR",
    EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR",
  } as const;
  
  export type ErrorCode =
    (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
